version: '3'

services:
  mysql:
    platform: linux/amd64
    image: mysql
    container_name: mysql_test
    ports:
     - 3306:3306
    expose:
     - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

    # volumes:
    #  - ./data:/var/lib/mysql
