version: '3'

services:
  python-model:
    image: jp-hacks-python-model
    build: ./make_model/
    container_name: jp-model
    volumes:
      - ./make_model/work/:/app/
    environment:
      MYSQL_ROOT_PASSWORD: pass
    expose: 
      - "80"
    tty: true
    depends_on:
      - mysql
      - python-main


  mysql:
    image: jp-hacks-mysql
    build: ./db/
    container_name: jp-mysql
    expose:
     - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: jp-db
      # MYSQL_USER: user
      # MYSQL_PASSWORD: pass
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    tty: True

  python-main:
    image: jp-hacks-python-main
    build: ./main/
    container_name: jp-main
    volumes:
      - ./main/work/:/app/
    ports: 
      - 80:80
    environment:
      MYSQL_ROOT_PASSWORD: pass
    depends_on:
      - mysql
    tty: True

