version: '3'

services:
  # python-model:
  #   image: jp-hacks-python-model
  #   build: ./make_model/
  #   container_name: jp-model
  #   expose: 
  #     - "80"
  #   tty: true


  mysql:
    image: jp-hacks-mysql
    build: ./db/
    container_name: jp-mysql
    expose:
     - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      # MYSQL_USER: user
      # MYSQL_PASSWORD: pass
    # volumes:
    #  - ./data:/var/lib/mysql

  # python-main:
  #   image: jp-hacks-python-main
  #   build: ./main
  #   container_name: jp-main
  #   ports: 
  #     - 80:80
  #   environment:
  #     MYSQL_ROOT_PASSWORD: pass
