FROM python

WORKDIR /app
COPY ./work/ /app/

RUN pip install Flask
RUN pip install pandas
RUN pip install sqlalchemy
RUN pip install mysql-connector-python
RUN pip install requests


#CMD ["python", "hoge.py"]